#########################################################################
# 다중 프로파일을 이용한 환경별 스프링 부트 애플리케이션 설정 적용
#########################################################################

spring:
  profiles:
    active:
      - dev
    group:
      dev: common, dev