#########################################################################
# 공통 환경 설정
#########################################################################

# 프로파일 명칭 지정
spring:
  config:
    activate:
      on-profile:
        - common
  application:
    name: precthon-demo
  # 콘솔에 출력되는 배너 끄기
  main:
    banner-mode: OFF
  # 웹 브라우저의 새로고침을 통한 화면단 변경 이력 반영을 위한 타임리프 템플릿 파일과 정적 리소스 파일들의 경로 및 각각의 캐싱값 변경
  thymeleaf:
    prefix: file:src/main/resources/templates/
    suffix: .html
    mode: HTML
    # 개발이 완료되었을 경우엔 true로 변경
    cache: false
  web:
    resources:
      static-locations:
        - file:src/main/resources/static/
      cache:
        # 캐싱 기간을 36000분(=10시간)으로 지정
        period: 36000

# 마이바티스 설정
mybatis:
  # 마이바티스의 설정 파일의 경로 지정
  config-location: classpath:mybatis/config/mybatis-config.xml
  # 매퍼 파일에서 SQL 처리를 위한 클래스 매핑을 수행할 때, 매핑 대상이 되는 클래스의 이름만 기입하기 위한 패키지 경로 지정
  type-aliases-package: com.suihin.precthon.domain.**.dto
  # 자체적으로 정의한 마이바티스 타입 핸들러가 위치한 패키지 경로 지정
  type-handlers-package: com.suihin.precthon.global.common.mybatis
  # 마이바티스의 매퍼 파일의 경로 지정
  mapper-locations:
    - classpath:mybatis/mappers/*_mapper.xml

# 서버 설정
server:
  servlet:
    application-display-name: precthon
    # HTTP 요청 및 응답의 인코딩 정보 설정
    encoding:
      charset: UTF-8
      enabled: true
      force: true
