-- H2 In-Memory DB Tables

DROP TABLE IF EXISTS USER_ACCOUNTS CASCADE;

CREATE TABLE USER_ACCOUNTS (
    USER_ID                 INT                     GENERATED BY DEFAULT AS IDENTITY,
    EMAIL                   VARCHAR(40)             NOT NULL,
    PASSWORD                VARCHAR(255)            NOT NULL,
    NAME                    VARCHAR(15)             NOT NULL,
    NICKNAME                VARCHAR(20)             NOT NULL,
    PHONE                   VARCHAR(11)             NOT NULL,
    ACCOUNT_TYPE            VARCHAR(5)              NOT NULL,
    ENABLED                 TINYINT(1)              NOT NULL,
    DELETE_YN               CHAR(1)                 NOT NULL DEFAULT 'N',
    DELETED_AT              DATETIME                NULL,
    CREATED_AT              DATETIME                NOT NULL DEFAULT NOW(),
    PRIMARY KEY (USER_ID)
);


DROP TABLE IF EXISTS USER_ROLES CASCADE;

CREATE TABLE USER_ROLES (
    USER_ID                 INT                     NOT NULL,
    ROLE                    VARCHAR(15)             NOT NULL,
    CREATED_AT              DATETIME                NOT NULL DEFAULT NOW(),
    UPDATED_AT              DATETIME                NOT NULL
);


DROP TABLE IF EXISTS USER_PROFILES CASCADE;

CREATE TABLE USER_PROFILES (
    PROFILE_ID              INT                     GENERATED BY DEFAULT AS IDENTITY,
    USER_ID                 INT                     NOT NULL,
    PROFILE_IMG_URL         VARCHAR(255)            NOT NULL,
    BIO                     VARCHAR(150)            NOT NULL,
    CITY                    VARCHAR(15)             NOT NULL,
    UNIV                    VARCHAR(45)             NOT NULL,
    CREATED_AT              DATETIME                NOT NULL DEFAULT NOW(),
    UPDATED_AT              DATETIME                NOT NULL,
    PRIMARY KEY (PROFILE_ID)
);


DROP TABLE IF EXISTS LOGIN_HISTORY CASCADE;

CREATE TABLE LOGIN_HISTORY (
    HISTORY_ID              INT                     GENERATED BY DEFAULT AS IDENTITY,
    USER_ID                 INT                     NOT NULL,
    CLIENT_IP               VARCHAR(15)             NOT NULL,
    USER_AGENT              VARCHAR(255)            NOT NULL,
    EVENT_TYPE              CHAR(1)                 NOT NULL,
    LOGIN_DATETIME          DATETIME                NOT NULL,
    LOGOUT_DATETIME         DATETIME                NULL,
    PRIMARY KEY (HISTORY_ID)
);